import Head from 'next/head';
import Banner from '../components/Banner';
import Row from '../components/Row';
import Sidebar from '../components/Sidebar';
import { Movie } from '../typings';
import requests from '../utils/requests';

interface Props {
  netflixOriginals: Movie[];
  trendingNow: Movie[];
  topRated: Movie[];
  actionMovies: Movie[];
  comedyMovies: Movie[];
  horrorMovies: Movie[];
  romanceMovies: Movie[];
  documentaries: Movie[];
}

const Home = ({
  netflixOriginals,
  actionMovies,
  comedyMovies,
  documentaries,
  horrorMovies,
  romanceMovies,
  topRated,
  trendingNow,
}: Props) => {
  return (
    <div className='flex h-screen bg-[rgb(34,34,34)]'>
      <Head>
        <title>Movie Data</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Sidebar />
      <main className='flex w-full h-full'>
        <div className='gridTemplate w-full'>
          <div className='banner w-full h-1/2 '>
            <Banner netflixOriginals={netflixOriginals} />
          </div>
          <div className='movieListTemplate w-full h-1/2 flex'>
            <div className='popularMovies w-1/2 h-full '>
              <Row title='Trending Now' movies={trendingNow} />
            </div>
            <div className='colMovies flex flex-col w-1/2'>
              <div className='newMovies w-full h-1/2 '>
                <h4 className='text-[#fff] text-3xl pt-3 pl-3'>Top Rated</h4>
              </div>
              <div className='favMovies w-full h-1/2 '>
                <h5 className='text-[#fff] text-3xl pt-3 pl-3'>Favorites</h5>
              </div>
            </div>
          </div>
        </div>
        {/* <Banner netflixOriginals={netflixOriginals} /> */}
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchDocumentaries).then((res) => res.json()),
  ]);

  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      trendingNow: trendingNow.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
      documentaries: documentaries.results,
    },
  };
};
